### PR TITLE
Add Go Concurrency paper by Tu, et al.

### PR DESCRIPTION
**Pull request by technosophos**
- [X] I have followed the [code of conduct](https://github.com/hwayne/awesome-cold-showers/blob/master/CODE_OF_CONDUCT.md).
- [X] I have followed the [contributing](https://github.com/hwayne/awesome-cold-showers/blob/master/CONTRIBUTING.md) guidelines and used the proper item format.
- [X] This is not a duplicate.
- [X] The resource is free.
- [X] The resource is rigorous because: (please list) It is an academic journal article published in ASPLOS 2019.
- [X] The resource is not obnoxious, condescending, etc.
- [X] My writup is respectful of both sides.
- [X] I've added reasonable caveats.
- [X] I've noted if the resource is a video, pdf, etc.

### CODE REVIEW

**Comment by hwayne** [comment]
Could you make the title `Understanding Real-World Concurrency Bugs in Go`? I should probably add that to the checklist. Also, an important caveat to the paper is that the types of bugs seen with channels and shared memory are different. Channels lead to more blocking bugs (deadlocks, dangling channels) while shared-memory lead to more nonblocking bugs (race conditions, dirty reads).

**Comment by technosophos** [comment]
Sure! So is the idea that the header is the _title of the paper_? I didn't pick up on that, but it totally makes sense.

**Comment by technosophos** [comment]
I added your suggestion verbatim, as I liked the way you worded it.

**Comment by hwayne** [comment]
Thank you!

**Pull request merged**
